// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAitxmZeXlVGzsF-vABAWG26YlNhRxeT7o',
    appId: '1:775925007414:web:39e335e0563acc3d1f0497',
    messagingSenderId: '775925007414',
    projectId: 'Select Car Wash-3afc5',
    authDomain: 'Select Car Wash-3afc5.firebaseapp.com',
    storageBucket: 'Select Car Wash-3afc5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2gQQdsM7B9FSytd4saTQT19ynRBFJJAc',
    appId: '1:775925007414:android:2c727a273753d59f1f0497',
    messagingSenderId: '775925007414',
    projectId: 'Select Car Wash-3afc5',
    storageBucket: 'Select Car Wash-3afc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsxbUgfFMx7GdbYfHvEL_ibCwEY9xryPQ',
    appId: '1:775925007414:ios:19501eae17a14fce1f0497',
    messagingSenderId: '775925007414',
    projectId: 'Select Car Wash-3afc5',
    storageBucket: 'Select Car Wash-3afc5.firebasestorage.app',
    iosBundleId: 'com.example.Select Car Wash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsxbUgfFMx7GdbYfHvEL_ibCwEY9xryPQ',
    appId: '1:775925007414:ios:19501eae17a14fce1f0497',
    messagingSenderId: '775925007414',
    projectId: 'Select Car Wash-3afc5',
    storageBucket: 'Select Car Wash-3afc5.firebasestorage.app',
    iosBundleId: 'com.example.Select Car Wash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAitxmZeXlVGzsF-vABAWG26YlNhRxeT7o',
    appId: '1:775925007414:web:f6741b972df80b471f0497',
    messagingSenderId: '775925007414',
    projectId: 'Select Car Wash-3afc5',
    authDomain: 'Select Car Wash-3afc5.firebaseapp.com',
    storageBucket: 'Select Car Wash-3afc5.firebasestorage.app',
  );
}
